#ENC[AES256_GCM,data:/LLua4HxABpE+6XDqf7/f+qpTScldPB56vC5I8VpBEkriPDeZQnlpW/QVq5exRh19l7aaZQ9NXBtF57B3E7ruw==,iv:q7456fVX1tMXadk6cuDvgSsLuTFJucT08Cy+AZadNhQ=,tag:7YePNdfI45cun4C2LFb+9A==,type:comment]
#ENC[AES256_GCM,data:kvhx7gFU60oYJYYOmNR9j4EYAJbSER2o20R5UhJ7IJl6pWiqd6OQ+XG58e8FMhbknjfrWG2X5w9T2mtS2gzzGxmOGkftPHTqlM/m1tE/CVI0,iv:csiFm6hpkpDKpU3/Mq/r3PRrCVdbZZ1NOHaZeJq6bh4=,tag:E2Qb5EpGjt+w+7K3/9byLQ==,type:comment]
#ENC[AES256_GCM,data:toLgWE/u3FidSV4S5OQG9AOEWW/kVAqU6jZeLikmrJ/OZo4KCB3YQ7mFrWdsps9BKCSH2pEBqIdOtpUk0Pfcp2K89/R4OoK5EgIj,iv:8r8IzOwxI+L+znK3Dt0hYSkvF6vMI0OJsIq1BsDuD0Q=,tag:vFN3dH4prh+2FJ7qABelcw==,type:comment]
#ENC[AES256_GCM,data:qCtsA1qWFlQADvDUas22boENlld0yBt7/4cVhKaKCSFLLPrK/DXohRkvdlQP4os=,iv:ljABdULCj1sDTXHyhdk628PVxtZ1QkteZPSzSWHNBqw=,tag:h+tQW9TKHBBxGDLdovLThw==,type:comment]
#
#ENC[AES256_GCM,data:Kn1yTypUy9nTTn8p7kfAMOmAF3c/ewv+b+ynXeuyHBg6ruxQW/J2CiLxI8R23jgG11n/j6E+Ja64ixMHXhIuuZPKvg==,iv:HtRNw2sSKHsLT0yolKrTYXuzGM4bGDwTWmTYtPxLvO4=,tag:bcdY9JympBvtAtkrpOa5ZQ==,type:comment]
#ENC[AES256_GCM,data:wIZqfkBin+2oSihjTSOLwfMWCkOtTODM5FMx4OWQtzMGsKakNkqW998g5KG6iIBFtkQygW/4CJL4Zic3uLsMkhYGq1+t7MvHyDh0,iv:DP2aspu/wBLBxsoq7IHSh83TOuxk94PIsmInK7eFJms=,tag:48azocMKcEm1ZglLYa3gbw==,type:comment]
#ENC[AES256_GCM,data:xFrPN/91lSzUz6RW7s3WPvBgcdfLhuwoRdy53zFKgAcxfvsfr7P1icU8LOqm54Wi9858ap/iG7/FV+8VROoSzEO3lcjzHUj/8w==,iv:2H3DXB+psULquIKULQEICC+qYSwT3D7sWK927llSy7w=,tag:Qr9D0dmkKm1jN2APKCOipA==,type:comment]
#ENC[AES256_GCM,data:f3+/+JEXyvjUS1tV8Ma79yPsYWXSf5u3tXAMAe+1iLwdxzwurdifZvrdpbGggXfB0cmTytCH93yCIeEeKtot/HiyMknhVKg36rx98C/V,iv:FuZQ+kD1yxqm2yaUVeozg5fmQTMouCxQUIZITfY/pQg=,tag:OqTHt1/OTudap2ysR/D+jQ==,type:comment]
#
#ENC[AES256_GCM,data:JMdSGivu5yvHKcTxi+P3Ia0dBd1EHYIlf8yvFuo6UaGlQX5RicuOdrTYMw/zldyJRA+sSWH9GA6Zfo9Jnq5iqG7imlYQ7BWmSA==,iv:4QIgJV6J9yRf+NHLU4vs+D9S9BtKhGG6eAT+5v5Z85Y=,tag:knzpMRUYL+v13ivl3xHcOQ==,type:comment]
#ENC[AES256_GCM,data:FBSOGAQBLr9gxs4uHuxNnl0/paYHvRjIq2qJmJ05KdpLVma9xzQM9OYpk3x/WDc=,iv:C9jJ0HtlDvXl/VLydEe1UYUGYiQm8biYkPFsB/IrT2c=,tag:h5Ohq2h3BdtAOFZcE8k6Ag==,type:comment]
ipa_groups:
    - name: ENC[AES256_GCM,data:bpoN,iv:dYLdUSqJ7ipj9V512LFvdqeALgnDO8dStCThP5ZNTSw=,tag:1blqp8GXany0uvQyDNR4Mg==,type:str]
      description: ENC[AES256_GCM,data:9BhatWxBOyzBpVStXjY2IM8l+P7YlIeGL7PzXdTgAjlw604YFVr3XiwfBQ==,iv:vSrtWNZGmWQrRS1S2AC/gene72Nkbz5zqrYp6xQX0tQ=,tag:oTouTcGz5gAKbQRwUj9zdw==,type:str]
ipa_users:
    - uid: ENC[AES256_GCM,data:j3maMMuCtQ==,iv:XPdbPN6uc7P6AS84nzZjjQ00EdwhvLPPh4gH3hgqOsc=,tag:KwvxmxtRDZSZeSVejxe4OQ==,type:str]
      first: ENC[AES256_GCM,data:CQnqlW+VmA==,iv:rbPHtAVC1Wj/+QRbmWbL3CvL+fFagt+d4p2XglzjRl4=,tag:8nRb/qI0lvFV7ZjUuAKbXw==,type:str]
      last: ENC[AES256_GCM,data:8mfk77pVokG+lGVd,iv:i8Ijv01PRq24XHoofj0E1A2GhmVG/dw7DM8o5maEHRE=,tag:85cV9zpmpbGTc0GUYM2OuA==,type:str]
      groups:
        - ENC[AES256_GCM,data:we3z,iv:/vKzsPdLeGW4VQnb9I6Z5wi6ea4+Y8E8Ste49G5dTaQ=,tag:/6Gb9F5240I5akxauubbrw==,type:str]
      shell: ENC[AES256_GCM,data:nBQtuCJrsTI4,iv:ekhX7f98zPooQVdNWk7I29vD/0RuPxQZH35KQwLdBWs=,tag:eWE1l/xcBoLfczaE7chegQ==,type:str]
#ENC[AES256_GCM,data:sey45bYYCkgLQ9wTmg8t/o/a4H7Bo0Re7S9VOWeka7kePsvPqJLr67pnbNq7uvWGb98Y0fvkbBMAxyHFQaIBx6qB7FhiC1A=,iv:Wrl4h7LbfPtEPINktB8p0OaeDz7j6k4d1iuf5Dq5N58=,tag:1p8Zuj3UUuti2wMo8QLBRg==,type:comment]
#ENC[AES256_GCM,data:tD/vHrBV6j8VfYj8eKFvihB63+htc6KQvCVrN0UQ0GswqRaSNsMAbvzimUIsbj+xAB3jgyieQGErY4FblK3EzcRv5280ydU=,iv:ZUBvl2TsnhGRJAXaVQxYt8ZOBd6xsXuNpk6pcCc0sKk=,tag:tpFnBgaNHDlwGVaxGC+jUA==,type:comment]
#ENC[AES256_GCM,data:Wg8HhZKvwhavAsqPKKHfxOc3ltySYPxaaGRCTX84Z3tY0ZZfheFQeeCfWJlm3woVJEMTEpQ=,iv:dMiQRxQ7hhQAzIbZ82VCyqMFqjV08e+i08RbSxc+PQ0=,tag:xsnklsGOOoK+i7fcDH1pFg==,type:comment]
ipa_hostgroups:
    - name: ENC[AES256_GCM,data:2XCoNb9NdLuZFQ==,iv:gr13/3DMThYqAY0e+8L11KB+8dzxJkBHeEOcpjcJsy8=,tag:Mw76z4lkbO+atWpYWAMXTQ==,type:str]
      description: ENC[AES256_GCM,data:7CFLd3CrFZwRitaLMXJfxizpJN+DvhFJpNbCkuA=,iv:5a8JJ7li6QU+e5JpVYW+UuebeSyySpsam15iYZH+9cM=,tag:v4lZWR5znh1JafvUnXP1sA==,type:str]
ipa_hbac_rules:
    - name: ENC[AES256_GCM,data:yFAyFZy/0N+a1WhycA==,iv:yfIVa+9gVpAGN+PrqneQ1ENE2453KhH5uE4mhacwykU=,tag:Jx3Nk/pRsP4KSehxTs5Qng==,type:str]
      description: ENC[AES256_GCM,data:ta1SR13fxqKw4zwFUPZnokhKqHxMfX1edeVuAAGUIgNPakqve66X5A==,iv:Y7XFz2cySzsFEc2BlOdAj1lfQO2pM8Muy6XCKXwa5pU=,tag:QVfoB4xhmAC8wg4nRxh5kg==,type:str]
      user_groups:
        - ENC[AES256_GCM,data:eX61,iv:PeDPpBbWO0vBLEGVdbghCaLqgo8crPIl+vzmHboRjl4=,tag:gsL4+aE4t5ryZK15r4WMOg==,type:str]
      host_groups:
        - ENC[AES256_GCM,data:Q00O/ihgwRa+yQ==,iv:GgJgq96wMKW21DVYfTEnhrC0nQjKIOx446fzXG+XMlE=,tag:RpCBOpzmidDB4HkQdFXIVw==,type:str]
      services:
        - ENC[AES256_GCM,data:AVOTCg==,iv:FKqNIzP0GCPSJO5J7ckET+DQEv63G/W9meDwzUbqod0=,tag:/Ua4p/mXQ1ng9DleATSP3A==,type:str]
        - ENC[AES256_GCM,data:DdXF/w==,iv:1ynEwQlAT1f3tja6/whjjYEHfvcs4otQ6TswJxG/4l4=,tag:qakC21zfbdK+wT5uTWy3yw==,type:str]
        - ENC[AES256_GCM,data:/b231K/P,iv:89VSIsNqTEPaCD+6lbnHKWXIDDt/wAz5CLAObLutRVg=,tag:7AdJNpAbdqMnhHZvI76F1w==,type:str]
ipa_sudo_rules:
    - name: ENC[AES256_GCM,data:DdwWATCcM3IBYxMfcGY=,iv:pAo/HHm9Q5MKr3h4CzLEWVjH9QCYtRs8qIxbF1h6ntA=,tag:xpMeSA2u7Zk+ziaqn4/cAA==,type:str]
      description: ENC[AES256_GCM,data:+Ve3yfh+CWjH1ml91ygrWkeq25AQ4bmbHj8mnZvKtUSkqmf7YK0N1DO2gbCCIR3gceEC7NDa/3Y=,iv:oFlt2ToRyXboGiWyTi1ijYLXiHQ/yQpZUVVLYifyiuA=,tag:47bWYtgkw6X5O6yclVDRwg==,type:str]
      user_groups:
        - ENC[AES256_GCM,data:QN0E,iv:QNCHlx5s04jdl2Z4mBpqIfs3diPItfhW5SbkGaqWWCQ=,tag:L/serQ8WbA3XevRrdnurZw==,type:str]
      host_groups:
        - ENC[AES256_GCM,data:N38waTFhhtYfKQ==,iv:DiOl1mYl/KJMYtudoa66VRh9ZH1qEO51XiR6Bn/boj0=,tag:efsOa9lFJ+MsXA/11f5XMg==,type:str]
      command_category: ENC[AES256_GCM,data:Hp83,iv:1zb6H9NG9YJj8RbQ1NgNvo0WnIiHYEqcXqXaKHbz+RU=,tag:7NXcA+UcdzvfPQ//PcNgiQ==,type:str]
      run_as_user_category: ENC[AES256_GCM,data:J+ir,iv:YZN0HyB2uYIoRsyeWNwNXpRgeR514gri97aIm/k8rB8=,tag:ZSrxOdRSIvT+SOBLXPxXpQ==,type:str]
      options:
        - ENC[AES256_GCM,data:6Pwa3/rVJa8JimIECw==,iv:H2Sf5lA2Qj/Dk1rhDsrLMM+L4guVHtTgNHEGzmwhbDQ=,tag:PKcsF+kXuyaXSI4TFnprGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcmlVcGV4N1loZnFtVm0w
            cmEyUFJoWFVzM1pqOFVDRDNtWXpaTXNiZ25nClhxa1BtT0dwaHpPVjU2bDFFbGVt
            MkZSNytnSnlMWGVwOXIyRTZtRTkxbjQKLS0tIFcvRDFTSE54YlRpR080Y1I1UE40
            a01MWEZyakRWNnZic3FMYUNhNk9FZVEKgm8VJewW6XtqZZDCi+93ofLhQXAW5d1P
            zB1rx1iq0b/JVHiNZ4XzSMMoqM4RUZlk06YMpaC4vzzTS8kl3B6Beg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ne5qwpqntg3m60qugynrqrjufxdajkxqt368rln4kdat6k5mz5mq9xnfzw
    lastmodified: "2026-06-19T09:08:56Z"
    mac: ENC[AES256_GCM,data:0TV4uKdzStDNWPv4VHSpP48ikfEOIwLkLZtzLBubGIn3B+1eswrW2EUA3d0hjnrKoOl4dcoFSThWnPiYzWXx2oR/B0rihGLA1jJcNSffquwCTVd2D3MPtF0aqhdjAWpZgRMWEcbnJAwWIEKzd4DQUtm60DT5TYHedLe08yCLQ1Y=,iv:Mn8WkbceRopotG4Q7lhJMnqR6aIcADGpTunaFGafYh4=,tag:J1JiNVaX/H1uF6BEWk8ycA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
