#ENC[AES256_GCM,data:EpqAmwr5kwho7ADpbGiXpJ7YHlIlEOzQeXoMm7nS+wbEMu5f0kMu8rOHlf/mcGwIO+EfcAnCdZyGSK1JFl4J,iv:n8hEyaPy7qjObt5vE05cgZXSvqCkgQLCVYRl7Fyy0vc=,tag:bTIkISfy+Pl56YS8KBmP9Q==,type:comment]
#ENC[AES256_GCM,data:b5Z/V/5560Af7G/rCjuzI5yA73/heN4cFs+gz66kZ57XUdrL1vcRqSaknsulQJdyn8JXsPC9odUsF6GqmDV7T9aH2hELwSVE8LmQh4KAkQ==,iv:3ar3HpFq9VZsdEuHCUs5J9gDEm+QT0isWKp3ePNpf6E=,tag:BZDY+g31bG5wZ3T3kBoTKQ==,type:comment]
#ENC[AES256_GCM,data:oMQwQ2zHaPo+8yq4iTDSors3H3EZxBjRAg5Nj0opxpalgYTDQuMsY/FYUfaxrYNoi5ozhV+G5Zs7/NFrWo7A/N3Y,iv:karBx5mzbCWJ/jVS1XWwE7SP9ziMia+M0Fxu51R9Kyc=,tag:sjN04hV8Yx8LdkB42ivbrA==,type:comment]
#ENC[AES256_GCM,data:zaPNqOBOUWAON85QrjrLJeV+fbPjY7Q8cWiQlJLJcqujqmhnqFXUG7uRuuM=,iv:7KJFzVbj09jMHPz8mJqMtFPsU2RYkYoVIt91AKXMCCo=,tag:fMP/qapiXGL/uxw+BuKDFQ==,type:comment]
#ENC[AES256_GCM,data:5OVFAxaei0ahvW9M0JWhDKxF9LdRfz9LDH6fErgivMqR0cNaBCVgZ2biJx5FEw==,iv:ZHAgFN7xYzhakmAuK7YEBPLOmiznXRDm+sjhUxyTHmQ=,tag:5JLylDShsoK21NZiqzPzNQ==,type:comment]
#
#ENC[AES256_GCM,data:XIF3CuYU7NGvO0DrVxq0IWMQeHYE0W4TjW9IBBIm7o67cUgRAOXcdkslYFrwvhqVKQdmYTUZE1LR3R//Ellhha3uL1aM2leGkRWV,iv:LG/iK6VMti4rwaqXrt4HokbAPuQLsSvr7c0TyFHaJp0=,tag:RbB/xKQOP3nQ+7l7b0/SJg==,type:comment]
#ENC[AES256_GCM,data:+Fhx4BvsPYcbO/R2Ueiw7gyIP6eL0n9NA5bXi9xqAS+mrvK72nOKuO2bPaMQOuTcfqnr6fG4dIPVxVJDYrssTuwJpEf/Zw==,iv:FHXjUig/6wplaw7zwAjIaCIfuyGErO2NtMYAfw0DX9s=,tag:7vjgNzTuD83drBskF0Oy9w==,type:comment]
#
#ENC[AES256_GCM,data:t1ZJrMtQvZPwsfupKyrbEt/V6WqR7u9wjreNkpix9nEkFUIC2rn4RE5Et7bFtMwrBxgdcC8yJsZFLy67+9hq/sbFZj9Tqn4N8d/Nuw==,iv:vgvGAuGObo7iFFCJAcO6UsrObU+mQIpl93wcDTFZ5vQ=,tag:ULBMvM1p95xGf1lpQLVrtw==,type:comment]
#ENC[AES256_GCM,data:YEiMbPU/2s+r3L/SLygyLT4j4UWKgg/2557TgVGqQN9aQO03c3Vup3Ah08eznDSMYYGb8l4HhsLAMQUXhWi95EtHNmjJ5mH0sknC,iv:sA/Uy5Ct/ji8RnZYU34eN0szHxSVtC4dwA+AB5mNtew=,tag:38QEGc96bZHMKhz61+W/qQ==,type:comment]
#ENC[AES256_GCM,data:uhvI1/C7WJFS33Wa0s5Uyk52WCugL99QuTLHi+4MJci/aJGPCU8Pg3Mh1vnVIgz6NdatBVLdew1g95k557ZCaDOwPua+xV015mY=,iv:5HE1Y1dcMxvtF3ZaZCSjNx3Fb9d5CZjhM/gJSFMwoL8=,tag:IQMFC9IzSSa0l6OFgCfCdA==,type:comment]
#ENC[AES256_GCM,data:gr+fZEdRVAN6p0LiHrb2nv5nwU55GSbDayFWDYcwGRj+DaZSFavZj01IjOYSUjrR,iv:qe57Yna3nLp3aRjjdQCeY3E9y0R7I49n8zQkhndKlXs=,tag:RMJNMGqz1XU9TW4ZRgLfgw==,type:comment]
#ENC[AES256_GCM,data:MISyBY9OAKYYBRCh2HiPl0iLKmQeWl4mwrhsjJXJyRbWok1V6c/Q2e7W4qjnQKwx,iv:NWiOznYydHrz2Ux+R/UpfScbCHm3J/UcNQ5xa+g0T34=,tag:85UD/MfGdPyy6z2TJN2cWA==,type:comment]
ipaadmin_principal: ENC[AES256_GCM,data:qYbEfy0=,iv:4Q0yAdplhI0jUA0/20R4clcL2DlnHaaGbRGNUx10Aos=,tag:K0JvSLg0l76y6B2gLQqKKA==,type:str]
#ENC[AES256_GCM,data:e+pvEc4GAWEtzrMNns/OsRmpK7xs9NKIseugO/ZzynIJOm75s5T0/Pk=,iv:9Mzg1oQ/KOj/A3kMWI1AqJUFsQPJt2H6/bzEFBPI26I=,tag:NIWin+wEWYuhH1nCQH3VEg==,type:comment]
ipaadmin_password: ENC[AES256_GCM,data:GvuWKo30wXnFwAQlEcwR2m8qig==,iv:ZUgIrJHyR5QyOyy0Sb4wx+lZzX+WIpcI3WdAo2iWIU0=,tag:quxQL85qvE/Da19llZHbfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WE1UdlhLYlpwWWFrTzhT
            b3RNbU8zbGlURUhIS01nOE9GRk5KTTlIa2tRCjhGMHRpQUt0ZFk1eFBXdW1jZzFq
            RkRHa2cxMitGTGNmVWREWHp4L3FmTmcKLS0tIG5BOWhwN1VNU0xMbElOUkppRkpv
            YlY4RnhlTnJ5RVEzb204eGc4MURrencKk8I5JpuGYRJEouKajbEtt+XLQTbJASmp
            FOZv/L1gJy7aneeeutxZLn5zj76ReZXfBvFKaYXeYi2fdTrZzYy1vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ne5qwpqntg3m60qugynrqrjufxdajkxqt368rln4kdat6k5mz5mq9xnfzw
    lastmodified: "2026-06-19T07:38:08Z"
    mac: ENC[AES256_GCM,data:/WJqP/WUv8uWbr3Gb3pHzkcHAVb2TbARpSgiTgAXVR66RZB3fCFSrtQZYJ9Pr91qFzyxXxWsBQzdlPdkQ/a2TV85GHRiWuLFGVkD9fmL/xl6TZAFE2gUOYWmu1X5LnPTy4zibXCKjbGcZrhk1Nw40YgFaPVAlV/o2v0AhvTeQ6w=,iv:a2nyuXqKBjwgnPvVBlV2IOu/P5GVoE7ajBeVsW2mSnM=,tag:SyTmMHGyO8JbdpBzcfOhXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
