#ENC[AES256_GCM,data:iF1mzVfwCfzNUQiG+xwYidSEo1Z1gBs3hsvpeVaCd5sFGPSxWXgK8ShPa+L7vzeaLzeo1P6Bd/1Lc1T7AUQH7Hg+Bcaz,iv:VlK6Df+BlDejLmVrR067awz1PFfQ+TdL5XEMC7mt9zU=,tag:3weZ8sh0+gEyg11t2XRM4g==,type:comment]
#ENC[AES256_GCM,data:5eISlFulDGuzLSdSrABs9Pf8ptR+b9ocThTY29rD9yQ8eOuV9W+Q8OhrbT4gL2LAKmoWGxa9Zz9wir6N6yz+1cBxdWnY1oMj7AtmeJ1jfEY0eS+qT+kobIZL0A==,iv:dJbvTEnRRsjcT8VY4XtV81CYAbA9QCfHJ2kSxM85tjA=,tag:8i8iYmmzP8qk3Nx3axAKDA==,type:comment]
#ENC[AES256_GCM,data:A+JXNbZEfLQbRwZyEyXfqKCL/4NaplP/ldXgW+TVpOKfwMzw8Nwn1ipPb5RbZ2CWuQJl4uzrD/SZEnJ9optRrYML,iv:gPDvofaQ9BpIpiqHSgznXvlQkiUMJDEWb12dhedH4+E=,tag:0mozLjqTT2ETGWqEHrgdIw==,type:comment]
#ENC[AES256_GCM,data:kP4ZxwS8q4qE3jEC9ok1k3aku064LJFwpWaXQEonzrDo9PDpnPnX6EhGrfI=,iv:tiz8G0Kx5GG+cY7IF0ETB/GK05kNtB+PrTZ0UMtva0U=,tag:IgTM1tJpK2MoTEhwTjJr9g==,type:comment]
#ENC[AES256_GCM,data:dPW9X4MTpnUq+UM5Bymr8JXalHlaJlagY6Sl6ocClRYmOYQpllvXOMF35PIv6H+qp5f4rA==,iv:pWyUAe8nLBSVO5Na16iVBN6eNJJQqxqQCOzScG6kAU8=,tag:K9eCm8kWhhAkpj49oZ5GlQ==,type:comment]
#
#ENC[AES256_GCM,data:zMjvaZwOsguLjHcMwR7iV7pxJshe1lisjxrnazcvBOzAqdAgT9axe0lMsnEPy+qug7CSn4UTzaE3YRe/b8QbS9ML9OqR7OB5rtBE,iv:nBEFjCWj0vV89qyeKE+oFn3V84xmLYQehEOH47cKROE=,tag:8gYMOBtxVnxokMhGpomptQ==,type:comment]
#ENC[AES256_GCM,data:y2E2f0Q4jVitFdE+ZKCRS0kDeObJNxev8EuhN4TvFLkDgahDhWwI7LprmgC7oECmV9yD9a4TB0PWgaL0yO92IagUdYVgLg==,iv:cI+7tNMwu2umzYTuhrxBVZx2PmjxoW+ZFaS99sQccSE=,tag:uqPZH6weKlcoU+FoDh8BAg==,type:comment]
#
#ENC[AES256_GCM,data:zK0HPn8OP6hdYq/80RQfA8rlcs7EmNVsoI61k6VBLc+TSoaipbKG5otkZTdk9t5YXUS2+bBuaOiP0+L77i7jbJg3wEuExNFg0H0=,iv:fvVG8CXKxOSDdOWJkJ2bqsfVoHyBlq4wabl0P8mJTk0=,tag:xh/MdDdC+vuPhcRE3qpeiA==,type:comment]
#ENC[AES256_GCM,data:gcvxtu6UTQXyqptuS7vbmEu3Q7PoiNGqgWKP/PaMJ1KRMr2ubxixL7xVVrpK6BIQeuGeBil9XrwIhrVto5xb,iv:IcuIeI4pQwmrYWxIl/dH8tiXZzeDhl1V30TY69yFJxE=,tag:nNwPLDwNOPHd3vdMVrvf4g==,type:comment]
#ENC[AES256_GCM,data:yvZvU6W9l7vu5k3LsfCcWb/C9KQ3yWrBg1BJbwhmNkMovJTvmpd1mwgIFUH0xnkUKp/7E73L2lnGvRDM9zuV49O9OTva0rU=,iv:Bq/4RjToPbAvaHhIWvwpuew0eQLVBtHmI9Ji68OwCcc=,tag:PLOiRy5vkJb+hCaE7MZbQw==,type:comment]
#ENC[AES256_GCM,data:twkrnFjQW0vglJ7acLPMBwfGBKa5F4uyXhRBYtp79pOvLErTm3WQMJgteaZ9PD18lCLib3uXUiBbkdRFLtKzrP8YSiw1,iv:kWzA8L1gxf0yV5+B5YosdyPJy+MGCP9SQI29BTYj9zM=,tag:/IkP8XOLEN4OzbzUBECyaA==,type:comment]
#ENC[AES256_GCM,data:WFs40YaYyVfIMFrtMOrLNofFsIdMGEf9im0HRe6ALZzAwb7fGYQpq2RnYAkYCYM6VMapWsb0AfFtDtImHvLN92Lv,iv:TzIAdnjpeCFuTp2I116X1a+tLOxdh6NBGiQtkKzCkEc=,tag:p7lIFVXRybl/OovG8xw5EQ==,type:comment]
ipadm_password: ENC[AES256_GCM,data:jj8lkfKoxVCImEH1jze/1fvldA==,iv:YFf6aLNLzco1Zi0YUHFy6Ib8MKA+B/u8zE6hVBbTKhg=,tag:IYZyDMyAvVvx2RR7u0oc0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UjJmRXVVQ0tIbHJ3eGJz
            d3RoQU1UejRJZ1BuT1JJTkc1aGNJZnI2Q3lNCmtxbEsyWG1td3dGaFc1bkRaREVV
            SWw5cktydHJFZ0N0MnlQbzZpVTdnVTQKLS0tIG4ya1FJRWduVHBQUDZvZFF6QTBE
            QVRIaUZ0OGFxamhLM29xNjg5Ulc5bUkKIup+fdzfWaPpUwCTz7jFSsCaU3MjRNNx
            EIIHdq+ejx82sTlKmL4QtgpKjhAbVV4JELlB4XN7fHYgO+Fp2XBK9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ne5qwpqntg3m60qugynrqrjufxdajkxqt368rln4kdat6k5mz5mq9xnfzw
    lastmodified: "2026-06-19T07:37:53Z"
    mac: ENC[AES256_GCM,data:XBTI4kFyIgEaQw1Bx0v/4Gi5WHcAH75nEbTJiPgRyj8dOn6KcjBmzQ+ZCG7Ej/AHdfFENkU/2oT468AIjqqZCS5argC9Ppoppk+XK7kAdJjGxfU565cZLzzAsEv2esVA5Cd5GCp9qrXhssERs6OyRwYcP7wDhEasfX+YagWI2yM=,iv:9WDp1xX9eY55d/g8zENbB6iKPkWwT4lBOIoAx4IUGPk=,tag:uBFvpoW/IEDE2MaPwNCKYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
